services:
  # App - sends resource operations to resources-server via Kinesis
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Application Configuration
      - NODE_ENV=development
      - PORT=3000
      
      # AWS Configuration for Kinesis
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      
      # Kinesis Configuration
      - KINESIS_STREAM_NAME=${KINESIS_STREAM_NAME:-resources-stream}
      
      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - JWT_EXPIRES_IN=1d
      
      # External AWS Cognito Configuration
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      
      # External AWS DynamoDB Configuration (Business Info)
      - DYNAMODB_BUSINESS_INFO_TABLE=${DYNAMODB_BUSINESS_INFO_TABLE:-business-info}
      - DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT}
      
      # External Citrus Sharding Service Configuration
      - CITRUS_SERVER_URL=${CITRUS_SERVER_URL:-http://citrus:8080}
      - CITRUS_API_KEY=${CITRUS_API_KEY}
      - CITRUS_TIMEOUT=${CITRUS_TIMEOUT:-5000}
      - CITRUS_RETRY_ATTEMPTS=${CITRUS_RETRY_ATTEMPTS:-3}
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
      
      # Logging and Monitoring
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      
      # Security Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:4000}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-1000}
    depends_on:
      citrus:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  # Resources Server - handles resource operations via Kinesis
  resources-server:
    build:
      context: ./resources-server
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    environment:
      # Application Configuration
      - NODE_ENV=development
      - PORT=3001
      
      # AWS Configuration for Kinesis
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      
      # Kinesis Configuration
      - KINESIS_STREAM_NAME=${KINESIS_STREAM_NAME:-resources-stream}
      
      # Notification Hub Service Configuration
      - ELIXIR_URL=http://notification-hub:4000
      
      # Citrus Sharding Configuration
      - CITRUS_SERVER_URL=${CITRUS_SERVER_URL:-http://citrus:8080}
      - CITRUS_API_KEY=${CITRUS_API_KEY}
      - CITRUS_TIMEOUT=${CITRUS_TIMEOUT:-5000}
      - CITRUS_RETRY_ATTEMPTS=${CITRUS_RETRY_ATTEMPTS:-3}
      
      # Cognito Configuration
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      citrus:
        condition: service_healthy
    networks:
      - app-network

  # Notification Hub - central hub for WebSocket communication
  notification-hub:
    build:
      context: ./elixir
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      # HTTP Configuration (for AI agent communication)
      - AI_AGENT_HTTP_URL=http://ai-agent-server:3000
      
      # Application Configuration
      - EXS_SECRET=${EXS_SECRET}
    depends_on:
      - resources-server
      - ai-agent-server
    networks:
      - app-network

  # AI Agent Server - processes AI messages
  ai-agent-server:
    build:
      context: ./ai-agent-server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      
      # HTTP Configuration
      - NOTIFICATION_HUB_HTTP_URL=http://notification-hub:4000
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
      # AI Configuration
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  # External Citrus Sharding Service
  citrus:
    image: citrus/sharding-service:latest
    ports:
      - "8080:8080"
    environment:
      # Citrus Configuration
      - CITRUS_ENV=development
      - CITRUS_LOG_LEVEL=${CITRUS_LOG_LEVEL:-info}
      
      # Database Configuration for Citrus-managed shards
      - CITRUS_DB_HOST=${CITRUS_DB_HOST:-postgres}
      - CITRUS_DB_PORT=${CITRUS_DB_PORT:-5432}
      - CITRUS_DB_USERNAME=${CITRUS_DB_USERNAME:-postgres}
      - CITRUS_DB_PASSWORD=${CITRUS_DB_PASSWORD:-postgres}
      - CITRUS_DB_NAME=${CITRUS_DB_NAME:-citrus}
      
      # Sharding Configuration
      - CITRUS_MAX_BUSINESSES_PER_SHARD=${CITRUS_MAX_BUSINESSES_PER_SHARD:-3}
      - CITRUS_SHARD_CREATION_ENABLED=${CITRUS_SHARD_CREATION_ENABLED:-true}
      - CITRUS_AUTO_SCALING_ENABLED=${CITRUS_AUTO_SCALING_ENABLED:-true}
      
      # API Configuration
      - CITRUS_API_KEY=${CITRUS_API_KEY}
      - CITRUS_CORS_ORIGINS=${CITRUS_CORS_ORIGINS:-http://localhost:3000}
      
      # Health Check Configuration
      - CITRUS_HEALTH_CHECK_INTERVAL=${CITRUS_HEALTH_CHECK_INTERVAL:-30}
      - CITRUS_SHARD_MONITORING_ENABLED=${CITRUS_SHARD_MONITORING_ENABLED:-true}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  # PostgreSQL for Citrus-managed shards
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citrus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Redis for AI Agent Server
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge