import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsOptional,
  IsDateString,
  IsArray,
  IsEnum,
} from 'class-validator';

// Report data model
export class ReportData {
  @ApiProperty({ description: 'Report name' })
  @IsString()
  name: string;

  @ApiProperty({
    description: 'Report type',
    enum: ['daily', 'weekly', 'monthly', 'quarterly', 'annual', 'custom'],
  })
  @IsEnum(['daily', 'weekly', 'monthly', 'quarterly', 'annual', 'custom'])
  type: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual' | 'custom';

  @ApiProperty({ description: 'Report description', required: false })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ description: 'Start date for report data' })
  @IsDateString()
  startDate: string;

  @ApiProperty({ description: 'End date for report data' })
  @IsDateString()
  endDate: string;

  @ApiProperty({ description: 'Metrics included in report' })
  @IsArray()
  @IsString({ each: true })
  metrics: string[];

  @ApiProperty({ description: 'Report filters applied', required: false })
  @IsOptional()
  filters?: Record<string, any>;

  @ApiProperty({ description: 'Report data/results', required: false })
  @IsOptional()
  data?: Record<string, any>;

  @ApiProperty({
    description: 'Report format',
    enum: ['json', 'pdf', 'excel', 'csv'],
  })
  @IsEnum(['json', 'pdf', 'excel', 'csv'])
  format: 'json' | 'pdf' | 'excel' | 'csv';

  @ApiProperty({
    description: 'Report status',
    enum: ['pending', 'generating', 'completed', 'failed'],
  })
  @IsEnum(['pending', 'generating', 'completed', 'failed'])
  status: 'pending' | 'generating' | 'completed' | 'failed';

  @ApiProperty({ description: 'Generated by user ID' })
  @IsString()
  generatedBy: string;

  @ApiProperty({ description: 'Generation timestamp' })
  @IsDateString()
  generatedAt: string;

  @ApiProperty({ description: 'File path/URL if saved', required: false })
  @IsOptional()
  @IsString()
  filePath?: string;
}
